name: check_logs

trigger:
- none

jobs:

- job: build
  displayName: build
  pool: 
    name: Default
  steps:
  - checkout: self
  - script: ls -al $(Build.SourcesDirectory)
  - task: CopyFiles@2
    displayName: 'Copy json into pipeline'
    inputs:
      contents: '$(Build.SourcesDirectory)/log_pipeline/settings.json'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
  - publish: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Publish json for later use'
    artifact: artifact

- job: gather_logs
  displayName: 'gather logs'
  dependsOn: build
  pool:
    name: Default
  steps:
  - download: current
    artifact: artifact
  - script: echo "##vso[task.setvariable variable=settings;]cat $(Pipeline.Workspace)/artifact/settings.json"
  - script: |
      echo "Show json settings"
      echo "$(settings)"
  # - task: PowerShell@2
  # call for 1000 pipeline runs and save response in file
  - script: |
      AUTH=$(echo -ne "$NPAUSER:$NPAPWD" | base64 --wrap 0)
      curl \
        --header "Content-Type: application/json" \
        --header 'Authorization: Basic $AUTH' \
        --request GET \
        'https://dev.azure.com/martamazurkiewicz/test/_apis/pipelines/1/runs?api-version=6.0-preview.1'
        -o runs.response 
    env:
      NPAPWD: $(npa_pwd)
      NPAUSER: $(npa_user)
  - script: tail -10 runs.response
